config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'
  resources :comments
  resources :types
  resources :categories
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/aboutus',    to: 'static_pages#aboutus'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'contact',  to: 'contact#index'
  post 'contact/confirm',  to: 'contact#confirm'
  post 'contact/thanks',  to: 'contact#thanks'
  get   '/typeahead' => 'items#typeahead_action'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :items
  resources :updates
  resources :reviews
  resources :relationships,       only: [:create, :destroy]
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews
  belongs_to :type
  belongs_to :category
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.paginate(page: params[:page])
  end

  def typeahead_action
        render json: Item.select("#{params[:title]}").where(Item.arel_table["#{params[:title]}".to_sym].matches("%#{params[:term]}%")).uniq
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    @reviews = @item.reviews.paginate(page: params[:page])
    if logged_in?
      @review = current_user.reviews.build
    else
      @review = Review.new
    end

  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        if session[:review]
          session[:review][:item_id] = Item.last.id
            if logged_in? && session[:review][:user_id] != "5"
              @review = current_user.reviews.build(session[:review])
            else
              @review = User.find(5).reviews.build(session[:review])
            end

            if @review.save
              flash[:success] = "レビューが作成されました"
              redirect_to root_url
            else
              @feed_items = []
              render 'static_pages/home' and return
            end
        end
        end
      else
        format.html { render :new } and return
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :author, :company, :type_id, :category_id, :sold_from, :photo)
    end

app/helpers/items_helper.rb
module ItemsHelper

def latest_item
@item = Item.first(3)
end

end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :type_id %>
    <%= form.collection_select :type_id, Type.all, :id, :name, :include_blank => true %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name, :include_blank => true %>
  </div>

  <div class="field">
    <%= form.label :sold_from %>
    <%= form.date_select :sold_from %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div class="col-xs-4 col-lg-3">
  <div class="item_list">
  <%= link_to item do %>
    <h3><%= item.title %></h3>
    <div>
      <% if item[:photo].blank? %>
       <%= image_tag "noimg.jpg" , :class => "img-responsive"%>
      <% else %>
       <%= image_tag item[:photo] , :class => "img-responsive"%>
      <% end %>
      <div class="bookinfo">
      <div><%= item.author %></div>
      <div><%= item.company %></div>
      <div><%= item.price %></div>
    </div>
    </div>
  <% end %>
  <div class="tagging">
    <span class="type"><%= link_to item.type.name, item.type %></span>
    <span class="category"><%= link_to item.category.name, item.category %></span>
    <% if logged_in? && current_user.admin?%>
      | <%= link_to 'Edit', edit_item_path(item) %>
      | <%= link_to "delete", item, method: :delete,
                                    data: { confirm: "本当に削除しますか" } %>
    <% end %>
  </div>
</div>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
<h1>作品タイトルの一覧からレビューを探す</h1>
</div>
  <% breadcrumb :items %>
<div class="container">
  <ul class="row row-eq-height">
      <%= render @items %>
</ul>
</div>

app/views/items/new.html.erb
<% provide(:title, "作品を追加する") %>
<div class="page-header">
  <h1>作品を追加する</h1>
  <p>是非ともレビューしたい作品を追加してください。</P>
</div>
<%= form_for(@item) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <span>タイトル</span>
    <%= f.text_area :title %>
    <span>概要</span>
    <%= f.text_area :description %>
    <span>新品価格</span>
    <%= f.number_field :price %>
    <span>著者</span>
    <%= f.text_area :author %>
    <span>出版社・提供</span>
    <%= f.text_area :company %>
    <span>媒体・メディア</span>
    <%= f.collection_select :type_id, Type.all, :id, :name, :include_blank => true %>
    <span>カテゴリー・ジャンル</span>
    <%= f.collection_select :category_id, Category.all, :id, :name, :include_blank => true %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/items/show.html.erb
<% provide(:title, @item.title) %>
<div class="page-header">
  <h1><%= @item.title %></h1>
</div>
<% breadcrumb :item, @item %>
<div class="container">
<div class="row">
<ul class="list-group col-xs-12 col-lg-8">
  <li class="list-group-item">
    <span><%= @item.description %></span>
  </li>
  <li class="list-group-item">
    <span class="topic">著者</span>
    <span><%= @item.author %></span>
  </li>
  <li class="list-group-item">
    <span class="topic">出版社・提供</span>
    <span><%= @item.company %></span>
  </li>
  <li class="list-group-item">
    <span class="topic">新品価格</span>
    <span><%= @item.price %></span>
  </li>
</ul>
<ul class="list-group col-xs-12 col-lg-4">
  <% if @item[:photo].blank? %>
   <%= image_tag "noimg.jpg" , :class => "img-responsive"%>
  <% else %>
   <%= image_tag @item[:photo] , :class => "img-responsive"%>
  <% end %>
</ul>
</div>

    <% if logged_in? %>
      <div class="row">
        <aside class="col-md-4">
          <section class="user_info">
            <%= render 'shared/user_info' %>
          </section>
          <section class="stats">
            <%= render 'shared/stats' %>
          </section>
          <section class="review_form">
            <%= render 'shared/review_form' %>
          </section>
        </aside>
      </div>
      <% else %>
      <section class="review_form">
        <%= render 'shared/review_form' %>
      </section>
      <div class="text-right">
        <span>会員なら本棚作成や報酬受取が可能です</span>
        <li class="btn btn-primary"><%= link_to "会員登録 ＞", signup_path %></li>
      </div>
    <% end %>

  <% if @item.reviews.any? %>
    <h3><%= @item.title %>のレビュー (<%= @item.reviews.count %>)</h3>
    <ul class="list-group">
      <%= render @reviews %>
    </ol>
    <%= will_paginate @reviews %>
  <% end %>
</ul>
</div>